### ISSUE TITLE
Install in sub-directory causes invitation link to be null?

### ISSUE THREAD

**Issue by fortiko** [ESTOS/meet#1]
- Installed from master in sub directory jitmeet-master/
- appears to generate wong "from user" names, as per console log:

``` js
init app.js:295
This appears to be Chrome strophejingle.bundle.js:27
status 1 app.js:37
connected app.js:33
onUserMediaSuccess strophejingle.bundle.js:139
PresError   muc.js:86
<presence xmlns=​"jabber:​client" to=​"55e86f76@www.acme.com/​55e86f76" from=​"jitmeet-master/​@www.acme.com/​55e86f76" type=​"error">​
<error code=​"404" type=​"cancel">​
<remote-server-not-found xmlns=​"urn:​ietf:​params:​xml:​ns:​xmpp-stanzas">​</remote-server-not-found>​
</error>​
</presence>​

- or am I missing something on the server/openfire side for MUC?
```

**Comment by fippo** [comment]
This looks like doJoin should do better checks about JID validity. For now, you probably need to adapt doJoin in app.js, I'll see if I can solve this more generically.

**Comment by fortiko** [comment]
Could you please confirm that what I need to set up on the openfire side for MUC? I receive the following exception upon connecting (I can see the video just fine, though):

``` java
2013.12.17 14:01:12 org.jivesoftware.openfire.http.HttpBindServlet - Client provided invalid session: 65a33f2e. [188.77.253.152]
2013.12.17 14:01:12 org.jivesoftware.openfire.session.LocalOutgoingServerSession - Error trying to connect to remote server: jitmeet-master(DNS lookup: jitmeet-master:5269)
java.net.UnknownHostException: jitmeet-master
        at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:175)
        at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:385)
        at java.net.Socket.connect(Socket.java:546)
        at org.jivesoftware.openfire.session.LocalOutgoingServerSession.createOutgoingSession(LocalOutgoingServerSession.java:280)
        at org.jivesoftware.openfire.session.LocalOutgoingServerSession.authenticateDomain(LocalOutgoingServerSession.java:167)
        at org.jivesoftware.openfire.server.OutgoingSessionPromise$PacketsProcessor.sendPacket(OutgoingSessionPromise.java:261)
        at org.jivesoftware.openfire.server.OutgoingSessionPromise$PacketsProcessor.run(OutgoingSessionPromise.java:238)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1146)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:701)

```

My config.js looks as follows

``` js
var config = {
    hosts: {
        domain: 'www.acme.com',
        muc: 'www.acme.com', // FIXME: use XEP-0030
        bridge: 'jitsi-videobridge.www.acme.com' // FIXME: use XEP-0030
    },
    useNicks: true,
    bosh: 'http://www.acme.com:7070/http-bind/' // FIXME: use xep-0156 for that
};
```

**Comment by fippo** [comment]
I don't know about openfire, but MUC and domain should be different...

**Comment by fortiko** [comment]
Installed it into a separate vhost root, and now it generates URL in the form of "meet.acme.com/zn1srmmeo1j1yvi"

However, the dialog resulting from "Invite Others" is still null.

In addition, I wonder how the httpd server would interpret an URL of the shape "meet.acme.com/zn1srmmeo1j1yvi" without any rewriting? Is there perhaps a htaccess missing, or is that precisely the point of a MUC url so that the MUC server/plugin would interpret "zn1srmmeo1j1yvi" as the chat room? Any ideas as to how to achieve that with Openfire?

**Comment by fippo** [comment]
This seems like you did not join the chatroom yet. @yanas: should we hide the toolbar before the entered.muc event?

actually there was a nginx rule example which explained how to do this... not sure where it got lost. It looks at follows:
    location ~ ^/([a-zA-Z0-9]+)$ {
        rewrite ^/(.*)$ / break;
    }
Without rewrites, the cheap and easy way to do this is to put the roomname to window.location.hash and get it from there. I.e. meet.acme.com/#zn1srmmeo1j1yv
Solves some problems, creates others.

**Comment by yanas** [comment]
On 17 Dec 2013, at 22:21, Philipp Hancke notifications@github.com wrote:

> This seems like you did not join the chatroom yet. @yanas: should we hide the toolbar before the entered.muc event?

Yes sure. I'm adding this to my todo list (with high priority).

**Comment by fippo** [comment]
d51b776c1ef9491210e68d8e11f7b8fe30ceb6f9 should allow you to implement your own strategy to determine the room node from the path with a function specified in config.js

Hope that solves the problem, if not please reopen!

**Comment by miguelurtado** [comment]
Hi, I have same problem. If enable getroomnode in config.js it is run else not run.
