### ISSUE TITLE
Which XMPP server should I use?

### ISSUE THREAD

**Issue by joudinet** [ESTOS/meet#2]
Hi,
I'm trying to configure (jit)meet such that it works offline. My goal is to have a multi-user videochat in a LAN.
As I have no experience with WebRTC and XMPP server, I'm a bit lost.
So far, I've installed an HTTP server (nginx) that serves a clone of jitmeet. It works online but not offline. I figured out from config.js that I should also install an XMPP server that supports BOSH, MUC and jitsi-videobridge extensions. Is it correct? If so, which server do you recommend (in particular if I have limited and distributed resources)?
From Wikipedia's comparison of XMPP servers, it seems ejabberd and prosody are good candidates but I don't know if they support jitsi-videobridge. For the latter, I've seen support from OpenFire only.

**Comment by fippo** [comment]
All of these should work. The http://prosody.im/discuss#chatroom is quite nice and helpful and I prefer it for my servers, also because it's quite resource efficient. 
The videobridge is added as an external component which is supported by all those servers.

**Comment by joudinet** [comment]
Thanks fippo. I've tried prosody and also got help from their chatroom. I manage to install all three XEPs (BOSH, MUC, and jitsi-videobridge) but (jit)meet refuses to connect to it. The JS console reports:
init app.js?v=3:461
This appears to be Chrome strophejingle.bundle.js?v=3:184
status 1 app.js?v=3:43
status 2 app.js?v=3:43
status 7 app.js?v=3:43
status 6 app.js?v=3:43

The prosody log are here:
http://pastebin.com/82i9zc93

What do I miss?

**Comment by joudinet** [comment]
It seems status 2 means Status.CONNFAIL. How can I get the reason for this failure?

**Comment by joudinet** [comment]
Ok, I needed to set authentication to "anonymous". Now it works.

**Comment by fippo** [comment]
ah, i'll add a note about this assumption later today. Thanks!
